OLED Module C
ThunFjsch/SmartWheels pull request #6
Opened 2023-12-06 10:19 UTC by leobeo-png

Replaced the code for the oled display with C code. The usage time is still not integrated in it.

2023-12-06 10:50 UTC, P1p1Kaka approved these changes
Looks good to me :)

2023-12-06 11:09 UTC, ThunFjsch requested changes

2023-12-06 11:09 UTC, ThunFjsch commented on src/OLEDScreen.cpp
> +#define SSD1306_ADDR  0x78
Is this a specific address you need? Maybe make clear what this address is for with a comment? As well as the choice for the hex value 0x78.

2023-12-06 11:09 UTC, ThunFjsch commented on src/OLEDScreen.cpp
> +enum time {
if it is commented out and not needed just delete it.

2023-12-06 11:09 UTC, ThunFjsch commented on src/OLEDScreen.cpp
> +	//u8g2_Setup_ssd1306_i2c_128x32_univision_f(&u8g2, U8G2_R0, u8x8_byte_avr_hw_i2caadasd, u8x8_avr_delay);
This comment can also be deleted

2023-12-06 11:09 UTC, ThunFjsch commented on src/OLEDScreen.cpp
> +int main (void)
delete the main here.

2023-12-06 11:09 UTC, ThunFjsch commented on src/OLEDScreen.h
> +#include <util/delay.h>
Do you need the util/delay?

2023-12-06 11:09 UTC, ThunFjsch commented on src/OLEDScreen.h
> +#include <avr/io.h>
this is imported in the main.c

2023-12-06 11:09 UTC, ThunFjsch commented on src/OLEDScreen.h
> +#include <stdbool.h>
this include can be applied in the main.c

2023-12-12 11:44 UTC, ThunFjsch approved these changes

2023-12-12 11:45 UTC, merged